---
- name: create the .aws direcotry for user vagrant
  file:
    path: "{{ (aws_user == 'root') | ternary('/root/.aws','/home/'+aws_user+'/.aws') }}"
    state: directory
    owner: "{{ aws_user }}"
    group: "{{ aws_user }}"
    mode: 0755

- name: create aws config
  template:
    src: aws.config.j2
    dest: "{{ (aws_user == 'root') | ternary('/root/.aws/config','/home/'+aws_user+'/.aws/config') }}"
    owner: "{{ aws_user }}"
    group: "{{ aws_user }}"
    mode: 0600

- name: create aws credentials
  template:
    src: aws.credentials.j2
    dest: "{{ (aws_user == 'root') | ternary('/root/.aws/credentials','/home/'+aws_user+'/.aws/credentials') }}"
    owner: "{{ aws_user }}"
    group: "{{ aws_user }}"
    mode: 0600
...
