---
# Specify which branch of Docker CE you want to install
# Options are 'stable', 'test', 'nightly'
docker_ce_branch: stable

docker_ce_repository_keyurl: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"

docker_ce_repository:
  redhat:
    - "https://download.docker.com/linux/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/{{ docker_ce_branch }}"
  debian:
    - "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_ce_branch }}"

docker_ce_exec_post_installation_steps: false

docker_ce_users: []
