---
- name: Install Nginx
  apt:
    name: "{{ nginx }}"
    state: present

- name: Configure Nginx to listen on port 8585
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - Restart Nginx

- name: Ensure Nginx service is enabled and started
  systemd:
    name: "{{ nginx }}"
    state: started
    enabled: yes
