# file: generic-users/meta/main.yml

galaxy_info:
  author: eric kemvou
  company: DEL
  description: Manage users
  min_ansible_version: 2.3.2
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - system

dependencies: []
