---
- name: install apache 
  hosts: #TBD(to be determine)
  become: yes
  become_user: root  
  roles:
     - users
     - patching
     - packages
     - docker
     - docker-compose
     - apache
     - reboot

