---
- name: configure bastion servers
  hosts: #TBD
  become: yes
  become_user: root  
  roles:
     - users
     - patching
     - packages
     - docker
     - docker-compose
     - terraform
     - kubens_kubectl
     - helm
     - awscli
     - reboot