---
- name: Configure bastion servers
  hosts: all
  become: yes
  become_user: root  
  roles:
    - users
    - patching 
    - packages 
    - docker
    - docker-compose
    - kubens_kubectl
    - git
    - terraform
    - helm 
    - awscli
    - reboot

   
  





