---
- name: configure bastion servers
  hosts: # TBD
  become: yes
  become_user: root  
  roles:
     - users 
     - patching 
     - packages 
     - awscli
     - helm
     - kubens_kubectl
     - terraform
     - reboot
