---
- name: install and configire gitalb
  hosts: # TBD
  become: yes
  become_user: root  
  roles:
     - users 
     - patching 
     - packages 
     - docker
     - docker-compose
     - gitlab
     - reboot
