---
- name: install and configire gitalb
  hosts: #TBD
  become: yes
  become_user: root  
  roles:
     -user
     -patching
     -packages
     -docker
     -docker-compose
     -gitlab
     -reboot