---
- name: install and configure nginx
  hosts: all
  become: yes
  become_user: root  
  roles:
     - users 
     - patching 
     - packages 
     - docker
     - docker-compose
     - nginx
     - reboot
     