---
- name: Install and configure Jenkins
  hosts: #TBD
  become: yes
  become_user: root  
  roles:
     - users
     - patching 
     - packages 
     - docker
     - docker-compose
     - terraform
     - gitlab
     - sonarqube
     - kubens_kubectl
     - awscli
     - jenkins
     - reboot