---
- name: install and configure nginx
  hosts: # TBD
  become: yes
  become_user: root  
  roles:
     - users
     - patching 
     - packages
     - docker
     - doxker-compose
     - nginx
     - reboot