---
- name: install and configure Sonarqube
  hosts: #TBD
  become: yes
  become_user: root  
  roles:
     -user
     -patching
     -packages
     -docker
     -docker-compose
     -sonarqube
     -jenkins
     -reboot