---
- name: install and configure Sonarqube
  hosts: # TBD
  become: yes
  become_user: root  
  roles:
     - users 
     - patching 
     - packages 
     - docker
     - docker-compose
     - sonarqube
     - reboot

     