---
# tasks file for jenkins
- name: Install jenkins 
  script: jenkins.sh 
  notify:
    - Restart Jenkins

- name: Ensure Jenkins service is enabled and started
  systemd:
    name: jenkins
    state: started
    enabled: yes
    
- name: Get Jenkins initial admin password
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_password


- name: Print Jenkins initial admin password
  debug:
    msg: "Jenkins initial admin password: {{ jenkins_password.stdout }}"
